name = "ecommerce-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"] # IMPORTANT for drizzle + bun

# This creates a fake R2 bucket locally, no cloud needed
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "ecommerce-uploads"
preview_bucket_name = "ecommerce-upload-preview"

# For public 
# [[r2_buckets]]
# binding = "R2_PUBLIC_BUCKET"
# bucket_name = "ecommerce-public"
# D1 not needed - we keep your Postgres
# Use vars for local dev
[vars]
S3_REGION = "auto"
RAZORPAY_KEY_ID='rzp_test_TQuu7mc6V9VydZ'
RAZORPAY_KEY_SECRET='rzolBh9uyvekuufWed7qddfQ'
COOKIE_NAME='_Host_session'
DATABASE_URL='postgresql://vikashadmin:dbpass@123@localhost:5432/ecommerce'

# RUSTFS_ACCESS_KEY='vikashsurin'
# RUSTFS_PUBLIC_URL='http://localhost:9000'
# RUSTFS_SECRET_KEY='rustfs@123'
# STORAGE_BUCKET_NAME='ecom_bucket'

# For local.env
[dev]
inspector = true
